# Generated by Django 4.2 on 2024-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
