# Generated by Django 4.2 on 2024-07-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_idea_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
