# Generated by Django 4.2 on 2024-07-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_notice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monetization',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idea', verbose_name='アイデア')),
            ],
        ),
    ]
